# Generated by Django 4.0.2 on 2025-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='services',
            field=models.CharField(blank=True, help_text='Ingresa los servicios separados por comas (ej: Consultoría, Desarrollo, Marketing)', max_length=200, null=True),
        ),
    ]
