# Generated by Django 4.0.2 on 2025-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_organization_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True, verbose_name='Descripción')),
                ('status', models.BooleanField(default=True, help_text='Indica si la categoría está activa o inactiva', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
    ]
