# Generated by Django 4.0.2 on 2025-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0005_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AddField(
            model_name='organization',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las categorías que aplican a esta organización', to='Empresa.Category', verbose_name='Categorías'),
        ),
    ]
