# Generated by Django 4.0.2 on 2025-06-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0006_alter_organization_options_organization_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Descripción personal o profesional', max_length=500, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='es-es', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones'),
        ),
    ]
